import { Inter } from "next/font/google";
import AudioPlayer from "../app/component/Player/AudioPlayer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative h-screen">
          {children}
          {/* <div className="absolute bottom-0 z-50">
            <AudioPlayer />
          </div> */}
        </div>
      </body>
    </html>
  );
}
